In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv("valNA2022stage2matches.csv", index_col=0)
matches.head()

,date,time,tier,type,tournament,score,opponent,team,GF,GA
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2,0
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2,0
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0,2
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2,0
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2,0

In [3]:
matches['score'] = matches['score'].str.replace('-',' : ')
new = matches["score"].str.split(":", expand = True)
matches["GF"] = new[0]
matches["GA"] = new[1]
matches["GF"] = matches["GF"].str.replace('\xa0',' ')
matches.head()

,date,time,tier,type,tournament,score,opponent,team,GF,GA
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2,0
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2,0
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0,2
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2,0
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2,0

In [4]:
matches["GF"] = pd.to_numeric(matches["GF"], errors='coerce')
matches["GA"] = pd.to_numeric(matches["GA"], errors='coerce')
matches.head()

,date,time,tier,type,tournament,score,opponent,team,GF,GA
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2.0,0.0
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2.0,0.0
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0.0,2.0
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2.0,0.0
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2.0,0.0

In [5]:
matches['result'] = np.where(matches["GF"] > matches["GA"], "W", "L")
matches.head()

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2.0,0.0,W
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2.0,0.0,W
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0.0,2.0,L
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2.0,0.0,W
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2.0,0.0,W

In [6]:
matches.dropna(inplace = True)
matches.dtypes

date           object
time           object
tier           object
type           object
tournament     object
score          object
opponent       object
team           object
GF            float64
GA            float64
result         object
dtype: object

In [7]:
matches['opponent'] = matches['opponent'].astype(str)
matches['team'] = matches['team'].astype(str)
matches.dtypes

date           object
time           object
tier           object
type           object
tournament     object
score          object
opponent       object
team           object
GF            float64
GA            float64
result         object
dtype: object

In [8]:
matches.head()

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2.0,0.0,W
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2.0,0.0,W
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0.0,2.0,L
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2.0,0.0,W
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2.0,0.0,W

In [9]:
matches.shape

(1132, 11)

In [10]:
matches["team"].value_counts()

Sentinels            149
TSM                  141
Cloud9               138
Luminosity Gaming    110
100 Thieves          100
NRG                   99
FaZe Clan             91
XSET                  89
Ghost Gaming          83
Evil Geniuses         78
The Guard             33
OpTic Gaming          21
Name: team, dtype: int64

In [11]:
matches[matches["team"] == "OpTic Gaming"].sort_values("date")

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result
20,2022-02-13,13:00 PST,A-Tier,Online,VCT 2022: North America Challengers 1 - Group ...,1 : 2,RISE,OpTic Gaming,1.0,2.0,L
19,2022-02-20,13:20 PST,A-Tier,Online,VCT 2022: North America Challengers 1 - Group ...,2 : 0,NRG,OpTic Gaming,2.0,0.0,W
18,2022-02-26,13:10 PST,A-Tier,Online,VCT 2022: North America Challengers 1 - Group ...,2 : 1,SEN,OpTic Gaming,2.0,1.0,W
17,2022-03-06,16:20 PST,A-Tier,Online,VCT 2022: North America Challengers 1 - Group ...,1 : 2,V1,OpTic Gaming,1.0,2.0,L
16,2022-03-13,14:50 PST,A-Tier,Online,VCT 2022: North America Challengers 1 - Group ...,2 : 0,PK,OpTic Gaming,2.0,0.0,W
15,2022-03-17,15:45 PST,A-Tier,Online,VCT 2022: North America Stage 1 Challengers,2 : 1,XSET,OpTic Gaming,2.0,1.0,W
14,2022-03-19,12:10 PST,A-Tier,Online,VCT 2022: North America Stage 1 Challengers,2 : 1,C9,OpTic Gaming,2.0,1.0,W
13,2022-03-25,12:10 PST,A-Tier,Online,VCT 2022: North America Stage 1 Challengers,2 : 0,TGRD,OpTic Gaming,2.0,0.0,W
12,2022-03-27,12:15 PST,A-Tier,Online,VCT 2022: North America Stage 1 Challengers,2 : 3,TGRD,OpTic Gaming,2.0,3.0,L
11,2022-04-10,20:45 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,0 : 2,XIA,OpTic Gaming,0.0,2.0,L
10,2022-04-12,19:15 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,2 : 0,KRÜ,OpTic Gaming,2.0,0.0,W
9,2022-04-13,17:15 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,2 : 0,XIA,OpTic Gaming,2.0,0.0,W
8,2022-04-15,21:00 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,2 : 1,TGRD,OpTic Gaming,2.0,1.0,W
7,2022-04-17,17:10 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,2 : 1,DRX,OpTic Gaming,2.0,1.0,W
6,2022-04-22,17:15 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,1 : 2,LLL,OpTic Gaming,1.0,2.0,L
5,2022-04-23,17:15 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,3 : 0,ZETA,OpTic Gaming,3.0,0.0,W
4,2022-04-24,17:15 GMT,S-Tier,Offline,VCT 2022: Stage 1 Masters - Reykjavík,3 : 0,LLL,OpTic Gaming,3.0,0.0,W
3,2022-05-14,16:10 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,FaZe,OpTic Gaming,2.0,0.0,W
2,2022-05-22,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 1,C9,OpTic Gaming,2.0,1.0,W
1,2022-05-28,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,SEN,OpTic Gaming,2.0,0.0,W
0,2022-06-03,23:55 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,1 : 2,EG,OpTic Gaming,1.0,2.0,L

In [12]:
matches["tournament"].value_counts()

VCT 2022: North America Challengers 2 - Group Stage    48
VCT 2022: North America Challengers 1 - Group Stage    45
T1 x Nerd Street Gamers Showdown                       29
VCT 2022: NA Stage 2 Challengers - Open Qualifier 1    27
FaZe Clan Invitational                                 26
                                                       ..
Knights Monthly Gauntlet - August                       2
Tyler1's Money Match                                    1
Knights Arena Monthly Gauntlet - October                1
NSG: Summer Championship - Open 2                       1
NSG: Winter Championship - Open 1                       1
Name: tournament, Length: 107, dtype: int64

In [13]:
matches["date"] = pd.to_datetime(matches["date"])

In [14]:
matches["target"] = (matches["result"] == "W").astype("int")

In [15]:
matches

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result,target
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2.0,0.0,W,1
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2.0,0.0,W,1
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0.0,2.0,L,0
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2.0,0.0,W,1
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2.0,0.0,W,1
...,...,...,...,...,...,...,...,...,...,...,...,...
84,2020-11-11,16:00 PST,A-Tier (Qual.),Online,UMG Tournament - Qualifier #1,0 : 2,FS,XSET,0.0,2.0,L,0
85,2020-11-04,20:15 EST,A-Tier,Online,First Strike North America - NSG Tournament,1 : 2,LG,XSET,1.0,2.0,L,0
86,2020-11-04,15:00 EST,A-Tier,Online,First Strike North America - NSG Tournament,0 : 2,C9 B,XSET,0.0,2.0,L,0
87,2020-10-27,17:00 PDT,A-Tier (Qual.),Online,NSG Tournament - Qualifier,0 : 2,Gen.G,XSET,0.0,2.0,L,0
88,2020-10-27,14:00 PDT,A-Tier (Qual.),Online,NSG Tournament - Qualifier,2 : 1,IMT,XSET,2.0,1.0,W,1

In [16]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [18]:
matches["day_code"] = matches["date"].dt.dayofweek

In [19]:
matches

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result,target,opp_code,hour,day_code
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2.0,0.0,W,1,100,20,6
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2.0,0.0,W,1,189,18,5
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0.0,2.0,L,0,179,16,5
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2.0,0.0,W,1,170,16,4
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2.0,0.0,W,1,10,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,2020-11-11,16:00 PST,A-Tier (Qual.),Online,UMG Tournament - Qualifier #1,0 : 2,FS,XSET,0.0,2.0,L,0,60,16,2
85,2020-11-04,20:15 EST,A-Tier,Online,First Strike North America - NSG Tournament,1 : 2,LG,XSET,1.0,2.0,L,0,85,20,2
86,2020-11-04,15:00 EST,A-Tier,Online,First Strike North America - NSG Tournament,0 : 2,C9 B,XSET,0.0,2.0,L,0,27,15,2
87,2020-10-27,17:00 PDT,A-Tier (Qual.),Online,NSG Tournament - Qualifier,0 : 2,Gen.G,XSET,0.0,2.0,L,0,72,17,1
88,2020-10-27,14:00 PDT,A-Tier (Qual.),Online,NSG Tournament - Qualifier,2 : 1,IMT,XSET,2.0,1.0,W,1,77,14,1

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [22]:
train = matches[matches["date"] < '2022-01-01']

In [23]:
test = matches[matches["date"] >= '2022-01-01']

In [24]:
predictors = ["opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
error = accuracy_score(test["target"], preds)

In [29]:
error

0.6085526315789473

In [30]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [31]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted   0    1
actual
0          23   82
1          37  162

In [32]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.6639344262295082

In [33]:
grouped_matches = matches.groupby("team")

In [34]:
group = grouped_matches.get_group("100 Thieves").sort_values("date")

In [35]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    #rolling_stats = group[cols].rolling(3, closed='left').mean()
    rolling_stats = group[cols].rolling(3).mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [36]:
cols = ["GF", "GA"]
new_cols = [f"{c}_rolling" for c in cols]

In [37]:
rolling_averages(group, cols, new_cols)

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result,target,opp_code,hour,day_code,GF_rolling,GA_rolling
97,2020-06-26,20:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,0 : 2,T1,100 Thieves,0.0,2.0,L,0,167,20,4,1.333333,0.666667
94,2020-06-27,20:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,12 : 13,IMT,100 Thieves,12.0,13.0,L,0,77,20,5,4.666667,5.000000
96,2020-06-27,14:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,1 : 2,FaZe,100 Thieves,1.0,2.0,L,0,64,14,5,4.333333,5.666667
95,2020-06-27,17:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,13 : 7,twat,100 Thieves,13.0,7.0,W,1,201,17,5,8.666667,7.333333
93,2020-07-08,10:00 PDT,Show M.,Online,Gamers For Equality,3 : 12,twat,100 Thieves,3.0,12.0,L,0,201,10,2,5.666667,7.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2022-05-07,17:45 EDT,A-Tier (Qual.),Online,VCT 2022: NA Stage 2 Challengers - Open Qualif...,2 : 0,AKRW,100 Thieves,2.0,0.0,W,1,10,17,5,2.000000,0.333333
3,2022-05-13,16:20 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,TGRD,100 Thieves,2.0,0.0,W,1,170,16,4,2.000000,0.333333
2,2022-05-21,16:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,TSM,100 Thieves,0.0,2.0,L,0,179,16,5,1.333333,0.666667
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,XSET,100 Thieves,2.0,0.0,W,1,189,18,5,1.333333,0.666667
0,2022-06-05,20:00 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,100 Thieves,2.0,0.0,W,1,100,20,6,1.333333,0.666667

In [38]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [39]:
matches_rolling

                     date       time     tier     type  \
team
100 Thieves 97 2020-06-26  20:00 PDT   A-Tier   Online
            94 2020-06-27  20:00 PDT   A-Tier   Online
            96 2020-06-27  14:00 PDT   A-Tier   Online
            95 2020-06-27  17:00 PDT   A-Tier   Online
            93 2020-07-08  10:00 PDT  Show M.   Online
...                   ...        ...      ...      ...
XSET        4  2022-04-17  14:45 EDT   C-Tier  Offline
            3  2022-05-14  18:35 EDT   A-Tier   Online
            2  2022-05-22  19:30 EDT   A-Tier   Online
            1  2022-05-28  18:15 EDT   A-Tier   Online
            0  2022-06-03  20:20 UTC   A-Tier   Online

                                                       tournament      score  \
team
100 Thieves 97                   T1 x Nerd Street Gamers Showdown      0 : 2
            94                   T1 x Nerd Street Gamers Showdown  12  :  13
            96                   T1 x Nerd Street Gamers Showdown      1 : 2
            95                   T1 x Nerd Street Gamers Showdown   13  :  7
            93                                Gamers For Equality   3  :  12
...                                                           ...        ...
XSET        4             NSG: Summer Championship - Philadelphia      2 : 0
            3   VCT 2022: North America Challengers 2 - Group ...      2 : 0
            2   VCT 2022: North America Challengers 2 - Group ...      2 : 0
            1   VCT 2022: North America Challengers 2 - Group ...      0 : 2
            0   VCT 2022: North America Challengers 2 - Group ...      2 : 1

               opponent         team    GF    GA result  target  opp_code  \
team
100 Thieves 97       T1  100 Thieves   0.0   2.0      L       0       167
            94      IMT  100 Thieves  12.0  13.0      L       0        77
            96     FaZe  100 Thieves   1.0   2.0      L       0        64
            95     twat  100 Thieves  13.0   7.0      W       1       201
            93     twat  100 Thieves   3.0  12.0      L       0       201
...                 ...          ...   ...   ...    ...     ...       ...
XSET        4      C9.A         XSET   2.0   0.0      W       1        29
            3      GHST         XSET   2.0   0.0      W       1        68
            2       NRG         XSET   2.0   0.0      W       1       100
            1      100T         XSET   0.0   2.0      L       0         1
            0      TGRD         XSET   2.0   1.0      W       1       170

                hour  day_code  GF_rolling  GA_rolling
team
100 Thieves 97    20         4    1.333333    0.666667
            94    20         5    4.666667    5.000000
            96    14         5    4.333333    5.666667
            95    17         5    8.666667    7.333333
            93    10         2    5.666667    7.000000
...              ...       ...         ...         ...
XSET        4     14         6    2.000000    0.333333
            3     18         5    2.000000    0.000000
            2     19         6    2.000000    0.000000
            1     18         5    1.333333    0.666667
            0     20         4    1.333333    1.000000

[1108 rows x 17 columns]

In [40]:
matches_rolling = matches_rolling.droplevel('team')

In [41]:
matches_rolling

,date,time,tier,type,tournament,score,opponent,team,GF,GA,result,target,opp_code,hour,day_code,GF_rolling,GA_rolling
97,2020-06-26,20:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,0 : 2,T1,100 Thieves,0.0,2.0,L,0,167,20,4,1.333333,0.666667
94,2020-06-27,20:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,12 : 13,IMT,100 Thieves,12.0,13.0,L,0,77,20,5,4.666667,5.000000
96,2020-06-27,14:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,1 : 2,FaZe,100 Thieves,1.0,2.0,L,0,64,14,5,4.333333,5.666667
95,2020-06-27,17:00 PDT,A-Tier,Online,T1 x Nerd Street Gamers Showdown,13 : 7,twat,100 Thieves,13.0,7.0,W,1,201,17,5,8.666667,7.333333
93,2020-07-08,10:00 PDT,Show M.,Online,Gamers For Equality,3 : 12,twat,100 Thieves,3.0,12.0,L,0,201,10,2,5.666667,7.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2022-04-17,14:45 EDT,C-Tier,Offline,NSG: Summer Championship - Philadelphia,2 : 0,C9.A,XSET,2.0,0.0,W,1,29,14,6,2.000000,0.333333
3,2022-05-14,18:35 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,GHST,XSET,2.0,0.0,W,1,68,18,5,2.000000,0.000000
2,2022-05-22,19:30 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 0,NRG,XSET,2.0,0.0,W,1,100,19,6,2.000000,0.000000
1,2022-05-28,18:15 EDT,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,0 : 2,100T,XSET,0.0,2.0,L,0,1,18,5,1.333333,0.666667
0,2022-06-03,20:20 UTC,A-Tier,Online,VCT 2022: North America Challengers 2 - Group ...,2 : 1,TGRD,XSET,2.0,1.0,W,1,170,20,4,1.333333,1.000000

In [42]:
matches_rolling.index = range(matches_rolling.shape[0])

In [43]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-02-11']
    test = data[data["date"] >= '2022-02-11']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

group stage challengers 1 February 11, 2022

In [44]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [45]:
error

0.8059701492537313

In [46]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [47]:
combined

      actual  predicted       date         team opponent result
73         0          0 2022-02-11  100 Thieves       C9      L
74         0          0 2022-02-20  100 Thieves     TGRD      L
75         1          1 2022-02-23  100 Thieves     ex-L      W
76         1          1 2022-02-24  100 Thieves    TSM.A      W
77         1          1 2022-02-24  100 Thieves      ABX      W
...      ...        ...        ...          ...      ...    ...
1103       1          1 2022-04-17         XSET     C9.A      W
1104       1          1 2022-05-14         XSET     GHST      W
1105       1          1 2022-05-22         XSET      NRG      W
1106       0          1 2022-05-28         XSET     100T      L
1107       1          0 2022-06-03         XSET     TGRD      W

[218 rows x 6 columns]

In [48]:
len(combined)

218

In [49]:
combined.team.unique()

array(['100 Thieves', 'Cloud9', 'Evil Geniuses', 'FaZe Clan',
       'Ghost Gaming', 'Luminosity Gaming', 'NRG', 'OpTic Gaming',
       'Sentinels', 'TSM', 'The Guard', 'XSET'], dtype=object)

In [50]:
combined.opponent.unique()

array(['C9', 'TGRD', 'ex-L', 'TSM.A', 'ABX', 'TSM', 'LG', 'XSET', 'EG',
       'TS', 'SoaR', 'AKRW', 'PK', 'Gen.G', 'SQ', 'NYFU', 'NRG', '100T',
       'OPTC', 'V1', 'FaZe', 'CD', 'UNK', 'LT', 'ZMM.B', 'Basilisk',
       'GHST', 'GK', 'SEN', '1337', 'RID', 'AME', 'DZ', 'BBG.A', 'VIRT',
       'T1', 'COL', 'Clan', 'RISE', 'XIA', 'KRÜ', 'DRX', 'LLL', 'ZETA',
       'BB', 'Reckaroo', 'RNG', 'C9.A', 'PRX', 'DXL', 'OXG.A'],
      dtype=object)

In [51]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Cloud9": "C9",
              "The Guard": "TGRD",
              "Luminosity Gaming": "LG",
              "Evil Geniuses": "EG",
              "FaZe Clan": "FaZe",
              "100 Thieves": "100T",
              "Sentinels": "SEN",
              "Ghost Gaming": "Ghost",
              "OpTic Gaming": "OPTC",}

mapping = MissingDict(**map_values)


map_values = {"C9": "Cloud9",
              "TGRD": "The Guard",
              "LG": "Luminosity Gaming",
              "EG": "Evil Geniuses",
              "FaZe": "FaZe Clan",
              "100T": "100 Thieves",
              "SEN": "Sentinels",
              "Ghost": "Ghost Gaming",
              "OPTC": "OpTic Gaming",}

In [52]:
combined["new_team"] = combined["team"].map(mapping)

In [53]:
combined

      actual  predicted       date         team opponent result new_team
73         0          0 2022-02-11  100 Thieves       C9      L     100T
74         0          0 2022-02-20  100 Thieves     TGRD      L     100T
75         1          1 2022-02-23  100 Thieves     ex-L      W     100T
76         1          1 2022-02-24  100 Thieves    TSM.A      W     100T
77         1          1 2022-02-24  100 Thieves      ABX      W     100T
...      ...        ...        ...          ...      ...    ...      ...
1103       1          1 2022-04-17         XSET     C9.A      W     XSET
1104       1          1 2022-05-14         XSET     GHST      W     XSET
1105       1          1 2022-05-22         XSET      NRG      W     XSET
1106       0          1 2022-05-28         XSET     100T      L     XSET
1107       1          0 2022-06-03         XSET     TGRD      W     XSET

[218 rows x 7 columns]

In [54]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [55]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-02-11,100 Thieves,C9,L,100T,1,1,Cloud9,100T,W,C9
1,0,0,2022-02-20,100 Thieves,TGRD,L,100T,1,0,The Guard,100T,W,TGRD
2,1,1,2022-02-24,100 Thieves,TSM.A,W,100T,1,1,TSM,100T,W,TSM
3,1,1,2022-02-24,100 Thieves,ABX,W,100T,1,1,TSM,100T,W,TSM
4,0,1,2022-02-24,100 Thieves,TSM,L,100T,1,1,TSM,100T,W,TSM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,0,1,2022-03-25,XSET,C9,L,XSET,1,1,Cloud9,XSET,W,C9
140,1,1,2022-05-14,XSET,GHST,W,XSET,0,1,Ghost Gaming,XSET,L,Ghost
141,1,1,2022-05-22,XSET,NRG,W,XSET,0,1,NRG,XSET,L,NRG
142,0,1,2022-05-28,XSET,100T,L,XSET,1,1,100 Thieves,XSET,W,100T
143,1,0,2022-06-03,XSET,TGRD,W,XSET,0,1,The Guard,XSET,L,TGRD

In [56]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    31
0     6
Name: actual_x, dtype: int64

In [57]:
22/24

0.9166666666666666

In [58]:
merged.to_csv("a.csv")